<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="len103" name="Regression" tests="328" failures="51" timestamp="1 Apr 2020 06:29:28 GMT" time="1240.909" errors="0">
  <testcase name="chargeCodeWithNegativeDetails" time="8.737" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeCodeWithNegativeDetails" time="2.883" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeCodeWithNegativeDetails" time="2.891" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeCodeWithNegativeDetails" time="2.875" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeCodeWithNegativeDetails" time="2.713" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeCodeWithNegativeDetails" time="2.739" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeCodeWithNegativeDetails" time="2.722" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeCodeWithNegativeDetails" time="2.732" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeCodeWithNegativeDetails" time="2.817" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidation" time="3.525" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidation" time="2.958" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidation" time="2.925" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidation" time="2.864" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidation" time="2.949" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.837" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.712" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.779" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.727" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.704" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.794" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.738" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.81" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.741" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.796" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.767" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.721" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.641" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.722" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.662" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="chargeTypeValidationForNegative" time="2.718" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="creationOfChargeCodeWithPositiveDetails" time="14.563" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.695" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.792" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.695" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.705" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.653" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.728" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.667" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.726" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="transactionFieldNegative" time="2.707" classname="com.idexcel.termloanservice.scripts.ChargecodeCRUD"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.835" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.694" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.752" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.653" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.675" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.726" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.827" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.7" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.755" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.681" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.742" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="3.751" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="3.858" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.813" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.742" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.787" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.724" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.697" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.619" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.8" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.718" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.688" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="3.016" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="termLoanDisburnsmentNegative" time="2.829" classname="com.idexcel.termloanservice.scripts.TermLoanDisburnsmentDate"/>
  <testcase name="OnetimeValueNEgative" time="6.465" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="OnetimeValueNEgative" time="6.203" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="OnetimeValueNEgative" time="6.068" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="OnetimeValueNEgative" time="8.082" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="OnetimeValueNEgative" time="6.558" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="OnetimeValueNEgative" time="5.949" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="OnetimeValueNEgative" time="7.556" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenalty" time="3.306" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenalty" time="2.851" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenalty" time="3.034" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenalty" time="2.853" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenalty" time="3.078" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenalty" time="2.94" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenaltyValue" time="3.123" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenaltyValue" time="3.038" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenaltyValue" time="2.976" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenaltyValue" time="3.013" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenaltyValue" time="2.955" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenaltyValue" time="2.896" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="latefeepenaltyValue" time="2.864" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="oneTimeManualFeeGet" time="16.603" classname="com.idexcel.termloanservice.scripts.OneTimeManualFee"/>
  <testcase name="termSetup" time="2.98" classname="com.idexcel.termloanservice.scripts.TermLoan">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [200] but found [400]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoan.termSetup_aroundBody0(TermLoan.java:82)
	at com.idexcel.termloanservice.scripts.TermLoan$AjcClosure1.run(TermLoan.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoan.termSetup(TermLoan.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termSetup -->
  <testcase name="termSetup" time="2.906" classname="com.idexcel.termloanservice.scripts.TermLoan">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [200] but found [400]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoan.termSetup_aroundBody0(TermLoan.java:82)
	at com.idexcel.termloanservice.scripts.TermLoan$AjcClosure1.run(TermLoan.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoan.termSetup(TermLoan.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termSetup -->
  <testcase name="termSetup" time="2.932" classname="com.idexcel.termloanservice.scripts.TermLoan">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [200] but found [400]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoan.termSetup_aroundBody0(TermLoan.java:82)
	at com.idexcel.termloanservice.scripts.TermLoan$AjcClosure1.run(TermLoan.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoan.termSetup(TermLoan.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termSetup -->
  <testcase name="termSetup" time="2.803" classname="com.idexcel.termloanservice.scripts.TermLoan">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [200] but found [400]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoan.termSetup_aroundBody0(TermLoan.java:82)
	at com.idexcel.termloanservice.scripts.TermLoan$AjcClosure1.run(TermLoan.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoan.termSetup(TermLoan.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termSetup -->
  <testcase name="termLoanInitialDateNegative" time="2.683" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.685" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="3.235" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.618" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.724" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.705" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.563" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.673" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.578" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.68" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.672" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.634" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.694" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.636" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.698" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.657" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.733" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.669" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.665" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.624" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.677" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.671" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.775" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.665" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.686" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.642" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.701" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.691" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.683" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.6" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.697" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.673" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.687" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.64" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.725" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.629" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.708" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg"/>
  <testcase name="termLoanInitialDateNegative" time="2.596" classname="com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verfiy status code for Initial date for negative date expected [400] but found [503]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verfiy status code for Initial date for negative date expected [400] but found [503]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg.termLoanInitialDateNegative_aroundBody0(TermLoanInitialPaymentdateNeg.java:62)
	at com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg$AjcClosure1.run(TermLoanInitialPaymentdateNeg.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanInitialPaymentdateNeg.termLoanInitialDateNegative(TermLoanInitialPaymentdateNeg.java:57)
	at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanInitialDateNegative -->
  <testcase name="AmortizationSchedule" time="2.587" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.AmortizationSchedule_aroundBody10(Amortization.java:191)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure11.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.AmortizationSchedule(Amortization.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- AmortizationSchedule -->
  <testcase name="AmortizationSchedule" time="2.692" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.AmortizationSchedule_aroundBody10(Amortization.java:191)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure11.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.AmortizationSchedule(Amortization.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- AmortizationSchedule -->
  <testcase name="amortization" time="2.667" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.amortization_aroundBody0(Amortization.java:52)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure1.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.amortization(Amortization.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- amortization -->
  <testcase name="amortizationGet" time="2.604" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationGet_aroundBody2(Amortization.java:77)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure3.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationGet(Amortization.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- amortizationGet -->
  <testcase name="amortizationGet" time="2.519" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationGet_aroundBody2(Amortization.java:77)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure3.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationGet(Amortization.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- amortizationGet -->
  <testcase name="amortizationSchelue" time="2.757" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationSchelue_aroundBody4(Amortization.java:98)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure5.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationSchelue(Amortization.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- amortizationSchelue -->
  <testcase name="amortizationScheluePost" time="2.594" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationScheluePost_aroundBody6(Amortization.java:126)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure7.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationScheluePost(Amortization.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- amortizationScheluePost -->
  <testcase name="amortizationScheluePutUPdateRegularDate" time="2.56" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationScheluePutUPdateRegularDate_aroundBody8(Amortization.java:152)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure9.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.amortizationScheluePutUPdateRegularDate(Amortization.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- amortizationScheluePutUPdateRegularDate -->
  <testcase name="undo" time="16.712" classname="com.idexcel.termloanservice.scripts.Amortization"/>
  <testcase name="undo" time="15.936" classname="com.idexcel.termloanservice.scripts.Amortization"/>
  <testcase name="undoFunctionality" time="2.881" classname="com.idexcel.termloanservice.scripts.Amortization">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.Amortization.undoFunctionality_aroundBody12(Amortization.java:245)
	at com.idexcel.termloanservice.scripts.Amortization$AjcClosure13.run(Amortization.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.Amortization.undoFunctionality(Amortization.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- undoFunctionality -->
  <testcase name="termLoanGetRequest" time="2.596" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	get termloan API statusCode expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	get termloan API statusCode expected [200] but found [502]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanAllGet.termLoanGetRequest_aroundBody0(TermLoanAllGet.java:69)
	at com.idexcel.termloanservice.scripts.TermLoanAllGet$AjcClosure1.run(TermLoanAllGet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanAllGet.termLoanGetRequest(TermLoanAllGet.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanGetRequest -->
  <testcase name="termLoanGetRequest" time="2.64" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	get termloan API statusCode expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	get termloan API statusCode expected [200] but found [502]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanAllGet.termLoanGetRequest_aroundBody0(TermLoanAllGet.java:69)
	at com.idexcel.termloanservice.scripts.TermLoanAllGet$AjcClosure1.run(TermLoanAllGet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanAllGet.termLoanGetRequest(TermLoanAllGet.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanGetRequest -->
  <testcase name="termLoanGetRequest" time="3.401" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet"/>
  <testcase name="termLoanGetRequest" time="2.75" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet"/>
  <testcase name="termLoanGetRequest" time="2.809" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet"/>
  <testcase name="termLoanGetRequest" time="2.689" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet"/>
  <testcase name="termLoanGetRequest" time="2.775" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet"/>
  <testcase name="termLoanGetRequest" time="3.714" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet"/>
  <testcase name="termLoanGetRequest" time="3.669" classname="com.idexcel.termloanservice.scripts.TermLoanAllGet"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.693" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.62" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.651" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.658" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="3.693" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.746" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.686" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.674" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.618" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.628" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.735" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.673" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.75" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.728" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.724" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.664" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.683" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.749" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.894" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.776" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.751" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.683" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.649" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.719" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.806" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.811" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.589" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.672" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.741" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.765" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.684" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.818" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.722" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.822" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.748" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.798" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.687" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.717" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.703" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.797" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.7" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.785" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="termLoanOrignalDateAsNegative" time="2.724" classname="com.idexcel.termloanservice.scripts.TermLoanOrignalDate"/>
  <testcase name="collateralCRUD" time="34.398" classname="com.idexcel.termloanservice.scripts.CollateralSetup"/>
  <testcase name="collateralCRUDDecimal" time="33.691" classname="com.idexcel.termloanservice.scripts.CollateralSetup"/>
  <testcase name="newInterestRateValidation" time="3.168" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="3.042" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.785" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.753" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.775" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.802" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.81" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.849" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.772" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.766" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.834" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.699" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.801" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.794" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.755" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.725" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.933" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.759" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.923" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.784" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.824" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.927" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="3.128" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.837" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.723" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.822" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.785" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.804" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="16.046" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="15.765" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="newInterestRateValidation" time="2.798" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.682" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.854" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.787" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.844" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.771" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.651" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.745" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.785" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.786" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.819" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.903" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.791" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.754" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.832" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.751" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="termLoanEditOperation" time="5.674" classname="com.idexcel.termloanservice.scripts.TermLoanEdit"/>
  <testcase name="reportGet" time="2.714" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.748" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.847" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="4.306" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.775" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.847" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.677" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.774" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.788" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.79" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="reportGet" time="2.742" classname="com.idexcel.termloanservice.scripts.TermLoanReports"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.75" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.662" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.675" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.87" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.821" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.724" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.828" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.866" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.824" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData_aroundBody2(TermLoanLoanNumber.java:80)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber$AjcClosure3.run(TermLoanLoanNumber.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData(TermLoanLoanNumber.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNumberWithNegativeData -->
  <testcase name="termLoanNumberWithNegativeData" time="2.821" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData_aroundBody2(TermLoanLoanNumber.java:80)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber$AjcClosure3.run(TermLoanLoanNumber.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData(TermLoanLoanNumber.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNumberWithNegativeData -->
  <testcase name="termLoanNumberWithNegativeData" time="2.759" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.736" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.654" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.798" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.756" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.914" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData_aroundBody2(TermLoanLoanNumber.java:80)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber$AjcClosure3.run(TermLoanLoanNumber.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData(TermLoanLoanNumber.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNumberWithNegativeData -->
  <testcase name="termLoanNumberWithNegativeData" time="2.695" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.878" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData_aroundBody2(TermLoanLoanNumber.java:80)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber$AjcClosure3.run(TermLoanLoanNumber.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData(TermLoanLoanNumber.java:74)
	at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNumberWithNegativeData -->
  <testcase name="termLoanNumberWithNegativeData" time="2.72" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.977" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData_aroundBody2(TermLoanLoanNumber.java:80)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber$AjcClosure3.run(TermLoanLoanNumber.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData(TermLoanLoanNumber.java:74)
	at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNumberWithNegativeData -->
  <testcase name="termLoanNumberWithNegativeData" time="3.825" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.7" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="2.727" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithNegativeData" time="3.901" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verfiy status code of Term loan Setup-Loan number Negative scenario expected [400] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData_aroundBody2(TermLoanLoanNumber.java:80)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber$AjcClosure3.run(TermLoanLoanNumber.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanNumber.termLoanNumberWithNegativeData(TermLoanLoanNumber.java:74)
	at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNumberWithNegativeData -->
  <testcase name="termLoanNumberWithNegativeData" time="3.793" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithPositiveData" time="2.927" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithPositiveData" time="2.797" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="termLoanNumberWithPositiveData" time="2.831" classname="com.idexcel.termloanservice.scripts.TermLoanLoanNumber"/>
  <testcase name="gracedays" time="2.917" classname="com.idexcel.termloanservice.scripts.GracePeriod">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.idexcel.termloanservice.scripts.GracePeriod.gracedays_aroundBody16(GracePeriod.java:393)
	at com.idexcel.termloanservice.scripts.GracePeriod$AjcClosure17.run(GracePeriod.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.GracePeriod.gracedays(GracePeriod.java:386)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gracedays -->
  <testcase name="termLoanNameWithNegativedata" time="6.685" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="6.744" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.671" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.805" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.835" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.73" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="2.606" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.642" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.607" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.678" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="3.659" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.771" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.605" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.613" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.612" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.73" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 33 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.586" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.67" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.568" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.652" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.585" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.576" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="3.645" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.711" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.621" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.572" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.666" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.689" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.691" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="2.548" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath.getList(JsonPath.java:375)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:52)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
	... 32 more
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="8.11" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.799" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.916" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.793" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.717" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.714" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.801" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="6.072" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.656" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.918" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="9.833" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verify Statuas code of Term loan setup loan name for Negative data expected [400] but found [201]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verify Statuas code of Term loan setup loan name for Negative data expected [400] but found [201]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:57)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="5.859" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.733" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="8.421" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verify Statuas code of Term loan setup loan name for Negative data expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verify Statuas code of Term loan setup loan name for Negative data expected [400] but found [500]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:57)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="5.789" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="8.022" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verify Statuas code of Term loan setup loan name for Negative data expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verify Statuas code of Term loan setup loan name for Negative data expected [400] but found [500]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:57)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
  <testcase name="termLoanNameWithNegativedata" time="5.769" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="5.766" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName"/>
  <testcase name="termLoanNameWithNegativedata" time="8.109" classname="com.idexcel.termloanservice.scripts.TermLoanLoanName">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is to verify Statuas code of Term loan setup loan name for Negative data expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	This is to verify Statuas code of Term loan setup loan name for Negative data expected [400] but found [500]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata_aroundBody0(TermLoanLoanName.java:57)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName$AjcClosure1.run(TermLoanLoanName.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.TermLoanLoanName.termLoanNameWithNegativedata(TermLoanLoanName.java:48)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- termLoanNameWithNegativedata -->
</testsuite> <!-- Regression -->
