<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="len103" name="com.idexcel.termloanservice.scripts.AutoAllocation" tests="8" failures="3" timestamp="26 May 2020 11:16:56 GMT" time="29.432" errors="0">
  <testcase name="autoAllocation" time="2.590" classname="com.idexcel.termloanservice.scripts.AutoAllocation"/>
  <testcase name="autoAllocationForManualFee" time="2.637" classname="com.idexcel.termloanservice.scripts.AutoAllocation">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	this is the status code for termloanResponse expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	this is the status code for termloanResponse expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.AutoAllocation.autoAllocationForManualFee_aroundBody4(AutoAllocation.java:98)
	at com.idexcel.termloanservice.scripts.AutoAllocation$AjcClosure5.run(AutoAllocation.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.AutoAllocation.autoAllocationForManualFee(AutoAllocation.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- autoAllocationForManualFee -->
  <testcase name="autoAllocation" time="2.727" classname="com.idexcel.termloanservice.scripts.AutoAllocation"/>
  <testcase name="autoAllocation" time="2.638" classname="com.idexcel.termloanservice.scripts.AutoAllocation"/>
  <testcase name="autoAllocation" time="2.615" classname="com.idexcel.termloanservice.scripts.AutoAllocation"/>
  <testcase name="autoAllocation" time="2.649" classname="com.idexcel.termloanservice.scripts.AutoAllocation"/>
  <testcase name="auto" time="10.968" classname="com.idexcel.termloanservice.scripts.AutoAllocation">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	this is the status code for termloanResponse expected [200] but found [409]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	this is the status code for termloanResponse expected [200] but found [409]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.AutoAllocation.auto_aroundBody6(AutoAllocation.java:161)
	at com.idexcel.termloanservice.scripts.AutoAllocation$AjcClosure7.run(AutoAllocation.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.AutoAllocation.auto(AutoAllocation.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- auto -->
  <testcase name="autoAllocationPeriod" time="2.608" classname="com.idexcel.termloanservice.scripts.AutoAllocation">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	this is the status code for termloanResponse expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	this is the status code for termloanResponse expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.idexcel.termloanservice.scripts.AutoAllocation.autoAllocationPeriod_aroundBody2(AutoAllocation.java:75)
	at com.idexcel.termloanservice.scripts.AutoAllocation$AjcClosure3.run(AutoAllocation.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:51)
	at com.idexcel.termloanservice.scripts.AutoAllocation.autoAllocationPeriod(AutoAllocation.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- autoAllocationPeriod -->
</testsuite> <!-- com.idexcel.termloanservice.scripts.AutoAllocation -->
